#!/bin/bash
if [ -z "$1" ]; then
    echo "usage: $(basename $0) start_note"
    exit
fi
note=$1
while [ 1 ]; do
    echo sending note $note
    chuck ../lib/*.ck cv_ocd_test.ck:$note
    note=$((note + 1))
done

