#!/usr/bin/python2
import time, sys, os
from globals import *
from timer import *
from touch_osc import *

if len(sys.argv) == 1:
    print('missing argument')
    sys.exit()
else:
    project_folder = sys.argv[1]
    init_file = project_folder + '/init.py'

if not os.path.exists(project_folder):
    print(project_folder + ' doesn\'t exist')
    sys.exit()
if not os.path.isdir(project_folder):
    print(project_folder + ' is not a directory')
    sys.exit()
elif not os.path.isfile(init_file):
    print('missing init file ' + init_file)
    sys.exit()


g.touch_osc_host = '192.168.0.6' # atte home
#g.touch_osc_host = '192.168.0.9' # britt home


g.init_file = init_file
g.project_folder = project_folder

execfile(init_file)

touch = touch_osc()
